AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-python

  Sample SAM application with Python Lambdas following DDD and Hexagonal Architecture

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Runtime: python3.9  # Ensure this is python3.8 or higher
    MemorySize: 1024
    Environment:
      Variables:
        PYTHONPATH: "/var/task/src/"

Resources:
  PatientAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.command.lambda.patient_appointment.lambda_handler
      Events:
        GetPatientAppointments:
          Type: Api
          Properties:
            Path: /appointments/{patientId}
            Method: get
    Metadata:
      BuildMethod: python3.9
      BuildProperties:
        RequirementsFile: requirements.txt

  AnotherLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.command.lambda.another_lambda_function.lambda_handler
      Events:
        AnotherEndpoint:
          Type: Api
          Properties:
            Path: /user-exists
            Method: get
    Metadata:
      BuildMethod: python3.9
      BuildProperties:
        RequirementsFile: requirements.txt
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
