name: Deploy to Production

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Validate
        run: sam validate

      - name: SAM Build
        run: sam build

      - name: Deploy to Production
        run: sam deploy --config-env production --no-confirm-changeset --no-fail-on-empty-changeset
