name: Deploy to AWS SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.sam-application-url }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build SAM application
        run: sam build --use-container

      # This step will pause the workflow until a reviewer approves the deployment.
      - name: Deploy SAM application
        run: sam deploy --confirm-changeset
