[tool.poetry]
name = "sam-app-python-poetry"
version = "0.1.0"
description = ""
authors = ["Ahmed <>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.6"
shortuuid = "^1.0.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
